# PyInstaller spec for the Friends of Duty content exporter.  -*- mode: python -*-
#
# onedir, deliberately. See Docs/EXPORTER_SINGLE_EXECUTABLE.md section 3.2:
# SteamPipe chunks at ~1 MB, so a onedir tree means a one-line exporter fix
# re-downloads a few hundred KB instead of the whole payload, and the exporter
# re-execs ITSELF once per host step -- a onefile build would pay its
# extraction cost twelve times per export.
#
# What is frozen here is only the shell: interpreter, stdlib, numpy, Pillow,
# Tcl/Tk, and the ssl/certifi/lzma set the Blender provisioner needs. The
# exporter's own modules and the whole tools/ closure ship as LOOSE source
# beside the binary, because pipeline._step_signature hashes those files to
# decide what to re-run -- freezing them would make every step's signature
# depend on the build rather than on the code.
#
# hiddenimports is generated by packaging/build_exporter.py, never hand-kept:
# because every tool is loose and executed through runpy, PyInstaller's
# analysis sees only fod_launcher.py and would otherwise miss the entire
# third-party surface of fifty tool modules.

import json
import os
import pathlib

REPO = pathlib.Path(os.environ["FOD_REPO_ROOT"]).resolve()
HIDDEN = json.loads(os.environ["FOD_HIDDEN_IMPORTS"])

a = Analysis(
    [str(REPO / "exporter" / "fod_launcher.py")],
    pathex=[str(REPO / "exporter"), str(REPO / "tools")],
    binaries=[],
    datas=[],
    hiddenimports=HIDDEN,
    hookspath=[],
    runtime_hooks=[],
    # Trimming what the payload will never touch. numpy.tests alone is ~14 MB,
    # and matplotlib/IPython arrive only as optional back-ends of other
    # packages -- nothing in this codebase imports them.
    excludes=[
        "matplotlib", "IPython", "pytest", "setuptools", "pip",
        "numpy.tests", "numpy.f2py", "PIL.ImageQt", "PyQt5", "PySide2",
    ],
    noarchive=False,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name="FriendsOfDutyExporter",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,          # UPX is a reliable way to look like malware to AV.
    console=True,       # The game drives this headless and reads stdout.
    disable_windowed_traceback=False,
    icon=None,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=False,
    name="_internal_build",
)
