#!/usr/bin/env python3
"""Which tools/ modules the export actually reaches.

`Builds/*/Exporter/tools/` currently ships every .py in tools/ — 24 of them
unreachable from any pipeline step, plus blender_asset_gen/ and ui_asset_gen/.
Dev tooling in a customer's install is not merely untidy: build_importer.py in
there prompts a player to install rustup.

The fix is an ALLOW-LIST, not a deny-list. A deny-list of `audit_*`, `report_*`,
`diagnose_*`, `render_*`, `test_*` is the obvious instrument and it provably
leaks — it matches neither extract_cod1_pavlov_entities.py nor
sync_cod1_unity_weapons.py, and says nothing about the two asset-generator
directories. Worse, it fails open: a new dev tool ships unless someone
remembers to name it.

So the manifest is computed, not maintained: start at the tools each pipeline
step actually invokes, follow local imports transitively, and ship exactly
that closure. tests/test_tools_manifest.py regenerates it and fails if the
checked-in file disagrees, so a new import can never silently leave a module
out and a new dev tool can never silently ship.
"""

from __future__ import annotations

import ast
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
TOOLS_DIR = REPO_ROOT / "tools"
EXPORTER_DIR = REPO_ROOT / "exporter"
MANIFEST_PATH = Path(__file__).resolve().parent / "tools_manifest.txt"


def entry_modules() -> list[str]:
    """Every tools/ module the exporter names or imports.

    Read out of the source rather than by calling build_argv(): several of
    those lambdas need real pipeline state (the props step resolves a JSON
    file the map import writes), so evaluating them here would mean faking an
    export just to list filenames. Every tool name reaches argv as a literal
    `"x.py"` handed to _python/_blender, or as `TOOLS_DIR / "x.py"` in
    signature_files, so a scan for string constants that resolve to a real
    file in tools/ catches all of them and cannot be fooled by control flow.

    exporter/*.py is scanned too, for the modules package.py and friends
    import directly rather than spawn.
    """
    names: set[str] = set()
    for source in EXPORTER_DIR.glob("*.py"):
        try:
            tree = ast.parse(source.read_text(encoding="utf-8"))
        except (OSError, SyntaxError):
            continue
        for node in ast.walk(tree):
            if isinstance(node, ast.Constant) and isinstance(node.value, str):
                value = node.value
                if value.endswith(".py") and (TOOLS_DIR / value).is_file():
                    names.add(value[:-3])
        names |= local_imports(source)
    return sorted(names)


def local_imports(module_path: Path) -> set[str]:
    """Sibling tools/ modules imported by `module_path`.

    Only names that resolve to a real file in tools/ count, so stdlib and
    third-party imports fall out on their own.
    """
    try:
        tree = ast.parse(module_path.read_text(encoding="utf-8"))
    except (OSError, SyntaxError):
        return set()
    found: set[str] = set()
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            for alias in node.names:
                found.add(alias.name.split(".")[0])
        elif isinstance(node, ast.ImportFrom):
            if node.level:  # relative import; not how tools/ refer to siblings
                continue
            if node.module:
                found.add(node.module.split(".")[0])
    return {name for name in found if (TOOLS_DIR / f"{name}.py").is_file()}


def closure() -> list[str]:
    pending = list(entry_modules())
    seen: set[str] = set()
    while pending:
        name = pending.pop()
        if name in seen:
            continue
        seen.add(name)
        pending.extend(local_imports(TOOLS_DIR / f"{name}.py") - seen)
    return sorted(seen)


def unreachable() -> list[str]:
    reachable = set(closure())
    return sorted(
        path.stem for path in TOOLS_DIR.glob("*.py")
        if path.stem not in reachable
    )


def render(modules: list[str]) -> str:
    return (
        "# Generated by packaging/tools_closure.py — do not edit by hand.\n"
        "# The tools/ modules the export actually reaches. Regenerate with\n"
        "#   python3 packaging/tools_closure.py --write\n"
        "# tests/test_tools_manifest.py fails if this disagrees with the\n"
        "# computed closure, so a new import cannot silently leave a module\n"
        "# out of the payload and a new dev tool cannot silently ship.\n"
        + "".join(f"{name}.py\n" for name in modules)
    )


def read_manifest() -> list[str]:
    return [
        line.strip()[:-3]
        for line in MANIFEST_PATH.read_text(encoding="utf-8").splitlines()
        if line.strip() and not line.startswith("#")
    ]


def main() -> int:
    import argparse

    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true",
                        help="rewrite packaging/tools_manifest.txt")
    parser.add_argument("--list-unreachable", action="store_true",
                        help="print the tools/ modules that never ship")
    arguments = parser.parse_args()

    modules = closure()
    if arguments.list_unreachable:
        for name in unreachable():
            print(name)
        return 0
    if arguments.write:
        MANIFEST_PATH.write_text(render(modules), encoding="utf-8")
        print(f"wrote {MANIFEST_PATH} ({len(modules)} modules, "
              f"{len(unreachable())} excluded)")
        return 0
    for name in modules:
        print(name)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
